In [6]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [7]:
# find contour: image, liste des contour, HI
# avant derniere case -2

In [8]:
lo = np.array([95, 80, 60])
hi = np.array([115, 255, 255])

In [9]:
# Définition d'une fonction pour détecter des éléments dans une plage de surfaces
def detect_inrange(image, surfaceMin, surfaceMax):
    points = []  # Liste pour stocker les informations sur les éléments détectés
    image = cv2.blur(image, (5, 5))  # Appliquer un flou pour réduire le bruit
    image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)  # Convertir l'image en espace colorimétrique HSV
    mask = cv2.inRange(image, lo, hi)  # Créer un masque en utilisant la plage spécifiée
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, None, iterations=2)  # Appliquer une opération de morphologie pour éliminer les petits artefacts
    elements = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[-2]  # Trouver les contours dans le masque
    elements = sorted(elements, key=lambda x: cv2.contourArea(x), reverse=True)  # Trier les contours par surface décroissante
    for element in elements:
        if surfaceMin < cv2.contourArea(element) < surfaceMax:  # Filtrer les contours par surface
            ((x, y), rayon) = cv2.minEnclosingCircle(element)  # Trouver le cercle minimum englobant le contour
            points.append(np.array([int(x), int(y), int(rayon), int(cv2.contourArea(element))]))  # Stocker les informations dans la liste
    return image, mask, points  # Renvoyer l'image d'origine, le masque et les informations sur les éléments


In [10]:
# Initialisation de la capture vidéo à partir de la caméra par défaut
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()  # Lecture d'une image depuis la caméra
    cv2.flip(frame, 1, frame)  # Retournement horizontal de l'image
    image, mask, points = detect_inrange(frame, 1000, 5000)  # Appel de la fonction de détection d'éléments dans la plage spécifiée
    cv2.circle(frame, (100, 100), 20, (0, 255, 0), 5)  # Dessiner un cercle sur l'image
    print(image[100][100])  # Afficher les valeurs des pixels à la position (100, 100) dans l'image convertie en HSV
    if len(points) > 0:
        # Dessiner un cercle autour du premier élément détecté
        cv2.circle(frame, (points[0][0], points[0][1]), points[0][2], (0, 255, 0), 2)
        # Afficher la surface de l'élément à côté du cercle
        cv2.putText(frame, str(points[0][3]), (points[0][0], points[0][1]), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 0, 0), 2, cv2.LINE_AA)
    if mask is not None:
        cv2.imshow('mask', mask)  # Afficher le masque
    cv2.imshow('image', frame)  # Afficher l'image avec les éléments détectés
    if cv2.waitKey(10) & 0xFF == ord('q'):  # Attendre la touche 'q' pour quitter la boucle
        break

cap.release()  # Libérer les ressources de la caméra
cv2.destroyAllWindows()  # Fermer toutes les fenêtres OpenCV

[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[150   2 255]
[130   3 255]
[150   2 255]
[150   2 255]
[130   3 255]
[130   3 255]
[135   2 255]
[135   2 255]
[120   1 253]
[120   1 253]
[120   2 254]
[120   2 254]
[ 80   3 251]
[ 80   3 251]
[  0   0 253]
[  0   0 253]
[105   4 255]
[105   4 255]
[ 50   3 252]
[ 50   3 252]
[ 75   2 252]
[ 75   2 252]
[ 60   3 252]
[ 60   3 252]
[ 60   4 252]
[ 60   4 252]
[ 90   3 252]
[ 90   3 252]
[ 83   4 251]
[ 83   4 251]
[ 75   4 251]
[ 75   4 251]
[ 66  